### ISSUE TITLE
I download your code but don't see fastlane script or not ? 

### ISSUE THREAD

**Issue by uthens** [czechboy0/XCSTutorialProject1#2]
Hi @czechboy0 

I followed by : https://honzadvorsky.com/articles/2015-08-04-xcs_tutorials_1_getting_started/

I have some problem on Jenkins + Fastlane setup don't work, but now i want to try on OSX server.
relate issue : https://github.com/fastlane/fastlane/issues/1230

and i search on google and found your blog, do you have any suggestion on this ?  OSX + Fastlane script ? 

Thanks you

**Comment by czechboy0** [comment]
Hi, have you read these two? Those should answer how to setup fastlane with Xcode Server 
https://honzadvorsky.com/articles/2015-08-17-17-30-xcode_server_tutorials_3_prebuild__postbuild_scripts/
https://honzadvorsky.com/articles/2015-09-14-15-00-xcode_server_hacks_3_install_cli_tools_for_xcsbuildd/

**Comment by uthens** [comment]
Thanks you so much
